name: Test workflow

on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  changes:
    runs-on: ubuntu-20.04

    # Set job outputs to values from filter step
    outputs:
      no_changes_eval: ${{ steps.filter.outputs.no_changes_eval }}
      changes_eval: ${{ steps.filter.outputs.changes_eval }}

    steps:
    # For pull requests it's not necessary to checkout the code
    - uses: dorny/paths-filter@v3
      id: filter
      with:
        filters: |
          no_changes_eval:
            - '!eval/**'
          changes_eval:
            - 'eval/**'

  smoke-test-gen:
    runs-on: ubuntu-20.04
    needs: changes
    if: needs.changes.outputs.no_changes_eval == 'true'
    steps:
      - run: echo "No eval changes detected!"

  smoke-test-eval:
    runs-on: ubuntu-20.04
    needs: changes
    if: needs.changes.outputs.changes_eval == 'true'
    steps:
      - run: echo "Eval changes detected!"
      - run: exit 1

  smoke-tests-completed:
    if: always()

    needs:
      - smoke-test-gen
      - smoke-test-eval

    runs-on: ubuntu-20.04

    steps:
    - name: Decide whether the needed jobs succeeded or failed
      uses: re-actors/alls-green@release/v1
      with:
        allowed-skips: smoke-test-gen, smoke-test-eval
        jobs: ${{ toJSON(needs) }}
